[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Configure secrets scanning
[secrets_scanning]
  enabled = true
  # Omit build output from secrets scanning since environment variables are handled safely
  omit_paths = ["dist/**", "build/**"]
  # Omit specific keys that are expected to be in the codebase
  omit_keys = ["VITE_SUPABASE_URL", "VITE_SUPABASE_ANON_KEY"]

# Environment variables (these should be set in Netlify dashboard, not here)
# VITE_SUPABASE_URL = "your-supabase-url"
# VITE_SUPABASE_ANON_KEY = "your-supabase-anon-key" 